#!/bin/bash

driver=$(readlink /sys/class/graphics/fb0/device/driver)
case $(basename $driver) in
  amdgpu|radeon)
    extra=""
    ;;
  *) #virtio-pci|gsgpu
    extra="env GALLIUM_DRIVER=softpipe"
    ;;
esac

if [ $(which pkexec) ]; then
	sudo $extra "/usr/bin/calamares" "$@" "-d"
else
	$extra /usr/bin/calamares "$@" "-d"
fi
